export const BASICTREATMENT_LIST_REQUEST = "BASICTREATMENT_LIST_REQUEST";
export const BASICTREATMENT_LIST_SUCCESS = "BASICTREATMENT_LIST_SUCCESS";
export const BASICTREATMENT_LIST_FAIL = "BASICTREATMENT_LIST_FAIL";

export const BASICTREATMENT_CREATE_REQUEST = "BASICTREATMENT_CREATE_REQUEST";
export const BASICTREATMENT_CREATE_SUCCESS = "BASICTREATMENT_CREATE_SUCCESS";
export const BASICTREATMENT_CREATE_FAIL = "BASICTREATMENT_CREATE_FAIL";

export const BASICTREATMENT_UPDATE_REQUEST = "BASICTREATMENT_UPDATE_REQUEST";
export const BASICTREATMENT_UPDATE_SUCCESS = "BASICTREATMENT_UPDATE_SUCCESS";
export const BASICTREATMENT_UPDATE_FAIL = "BASICTREATMENT_UPDATE_FAIL";

export const BASICTREATMENT_DELETE_REQUEST = "BASICTREATMENT_DELETE_REQUEST";
export const BASICTREATMENT_DELETE_SUCCESS = "BASICTREATMENT_DELETE_SUCCESS";
export const BASICTREATMENT_DELETE_FAIL = "BASICTREATMENT_DELETE_FAIL";
