export const BLOGS_LIST_REQUEST = "BLOGS_LIST_REQUEST";
export const BLOGS_LIST_SUCCESS = "BLOGS_LIST_SUCCESS";
export const BLOGS_LIST_FAIL = "BLOGS_LIST_FAIL";

export const BLOGS_CREATE_REQUEST = "BLOGS_CREATE_REQUEST";
export const BLOGS_CREATE_SUCCESS = "BLOGS_CREATE_SUCCESS";
export const BLOGS_CREATE_FAIL = "BLOGS_CREATE_FAIL";

export const BLOGS_UPDATE_REQUEST = "BLOGS_UPDATE_REQUEST";
export const BLOGS_UPDATE_SUCCESS = "BLOGS_UPDATE_SUCCESS";
export const BLOGS_UPDATE_FAIL = "BLOGS_UPDATE_FAIL";

export const BLOGS_DELETE_REQUEST = "BLOGS_DELETE_REQUEST";
export const BLOGS_DELETE_SUCCESS = "BLOGS_DELETE_SUCCESS";
export const BLOGS_DELETE_FAIL = "BLOGS_DELETE_FAIL";

export const COMMON_BLOGS_LIST_REQUEST = "COMMON_BLOGS_LIST_REQUEST";
export const COMMON_BLOGS_LIST_SUCCESS = "COMMON_BLOGS_LIST_SUCCESS";
export const COMMON_BLOGS_LIST_FAIL = "COMMON_BLOGS_LIST_FAIL";
