export const DOCTOR_LIST_REQUEST = "DOCTOR_LIST_REQUEST";
export const DOCTOR_LIST_SUCCESS = "DOCTOR_LIST_SUCCESS";
export const DOCTOR_LIST_FAIL = "DOCTOR_LIST_FAIL";

export const DOCTOR_LOGIN_REQUEST = "DOCTOR_LOGIN_REQUEST";
export const DOCTOR_LOGIN_SUCCESS = "DOCTOR_LOGIN_SUCCESS";
export const DOCTOR_LOGIN_FAIL = "DOCTOR_LOGIN_FAIL";
export const DOCTOR_LOGOUT = "DOCTOR_LOGOUT";

export const DOCTOR_REGISTER_REQUEST = "DOCTOR_REGISTER_REQUEST";
export const DOCTOR_REGISTER_SUCCESS = "DOCTOR_REGISTER_SUCCESS";
export const DOCTOR_REGISTER_FAIL = "DOCTOR_REGISTER_FAIL";

export const DOCTOR_VIEW_REQUEST = "DOCTOR_VIEW_REQUEST";
export const DOCTOR_VIEW_SUCCESS = "DOCTOR_VIEW_SUCCESS";
export const DOCTOR_VIEW_FAIL = "DOCTOR_VIEW_FAIL";

export const DOCTOR_UPDATE_REQUEST = "DOCTOR_UPDATE_REQUEST";
export const DOCTOR_UPDATE_SUCCESS = "DOCTOR_UPDATE_SUCCESS";
export const DOCTOR_UPDATE_FAIL = "DOCTOR_UPDATE_FAIL";

export const DOCTOR_DELETE_REQUEST = "DOCTOR_DELETE_REQUEST";
export const DOCTOR_DELETE_SUCCESS = "DOCTOR_DELETE_SUCCESS";
export const DOCTOR_DELETE_FAIL = "DOCTOR_DELETE_FAIL";

export const DOCTOR_VIEW_BY_ID_REQUEST = "DOCTOR_VIEW_BY_ID_REQUEST";
export const DOCTOR_VIEW_BY_ID_SUCCESS = "DOCTOR_VIEW_BY_ID_SUCCESS";
export const DOCTOR_VIEW_BY_ID_FAIL = "DOCTOR_VIEW_BY_ID_FAIL";

export const DOCTOR_UPDATE_BY_ID_REQUEST = "DOCTOR_UPDATE_BY_ID_REQUEST";
export const DOCTOR_UPDATE_BY_ID_SUCCESS = "DOCTOR_UPDATE_BY_ID_SUCCESS";
export const DOCTOR_UPDATE_BY_ID_FAIL = "DOCTOR_UPDATE_BY_ID_FAIL";
