export const FEEDBACK_GET_REQUEST = "FEEDBACK_GET_REQUEST";
export const FEEDBACK_GET_SUCCESS = "FEEDBACK_GET_SUCCESS";
export const FEEDBACK_GET_FAIL = "FEEDBACK_GET_FAIL";

export const FEEDBACK_CREATE_REQUEST = "FEEDBACK_CREATE_REQUEST";
export const FEEDBACK_CREATE_SUCCESS = "FEEDBACK_CREATE_SUCCESS";
export const FEEDBACK_CREATE_FAIL = "FEEDBACK_CREATE_FAIL";

export const FEEDBACK_UPDATE_REQUEST = "FEEDBACK_UPDATE_REQUEST";
export const FEEDBACK_UPDATE_SUCCESS = "FEEDBACK_UPDATE_SUCCESS";
export const FEEDBACK_UPDATE_FAIL = "FEEDBACK_UPDATE_FAIL";

export const FEEDBACK_DELETE_REQUEST = "FEEDBACK_DELETE_REQUEST";
export const FEEDBACK_DELETE_SUCCESS = "FEEDBACK_DELETE_SUCCESS";
export const FEEDBACK_DELETE_FAIL = "FEEDBACK_DELETE_FAIL";

export const FEEDBACK_GETFORADMIN_REQUEST = "FEEDBACK_GETFORADMIN_REQUEST";
export const FEEDBACK_GETFORADMIN_SUCCESS = "FEEDBACK_GETFORADMIN_SUCCESS";
export const FEEDBACK_GETFORADMIN_FAIL = "FEEDBACK_GETFORADMIN_FAIL";

export const FEEDBACK_UPDATEFORADMIN_REQUEST = "FEEDBACK_UPDATEFORADMIN_REQUEST";
export const FEEDBACK_UPDATEFORADMIN_SUCCESS = "FEEDBACK_UPDATEFORADMIN_SUCCESS";
export const FEEDBACK_UPDATEFORADMIN_FAIL = "FEEDBACK_UPDATEFORADMIN_FAIL";

export const FEEDBACK_DELETEFORADMIN_REQUEST = "FEEDBACK_DELETEFORADMIN_REQUEST";
export const FEEDBACK_DELETEFORADMIN_SUCCESS = "FEEDBACK_DELETEFORADMIN_SUCCESS";
export const FEEDBACK_DELETEFORADMIN_FAIL = "FEEDBACK_DELETEFORADMIN_FAIL";

export const COMMONFEEDBACK_GET_REQUEST = "COMMONFEEDBACK_GET_REQUEST";
export const COMMONFEEDBACK_GET_SUCCESS = "COMMONFEEDBACK_GET_SUCCESS";
export const COMMONFEEDBACK_GET_FAIL = "COMMONFEEDBACK_GET_FAIL";
