export const FILLING_LIST_REQUEST = "FILLING_LIST_REQUEST";
export const FILLING_LIST_SUCCESS = "FILLING_LIST_SUCCESS";
export const FILLING_LIST_FAIL = "FILLING_LIST_FAIL";

export const FILLING_CREATE_REQUEST = "FILLING_CREATE_REQUEST";
export const FILLING_CREATE_SUCCESS = "FILLING_CREATE_SUCCESS";
export const FILLING_CREATE_FAIL = "FILLING_CREATE_FAIL";

export const FILLING_UPDATE_REQUEST = "FILLING_UPDATE_REQUEST";
export const FILLING_UPDATE_SUCCESS = "FILLING_UPDATE_SUCCESS";
export const FILLING_UPDATE_FAIL = "FILLING_UPDATE_FAIL";

export const FILLING_DELETE_REQUEST = "FILLING_DELETE_REQUEST";
export const FILLING_DELETE_SUCCESS = "FILLING_DELETE_SUCCESS";
export const FILLING_DELETE_FAIL = "FILLING_DELETE_FAIL";
