export const MEDICALHISTORY_LIST_REQUEST = "MEDICALHISTORY_LIST_REQUEST";
export const MEDICALHISTORY_LIST_SUCCESS = "MEDICALHISTORY_LIST_SUCCESS";
export const MEDICALHISTORY_LIST_FAIL = "MEDICALHISTORY_LIST_FAIL";

export const MEDICALHISTORY_CREATE_REQUEST = "MEDICALHISTORY_CREATE_REQUEST";
export const MEDICALHISTORY_CREATE_SUCCESS = "MEDICALHISTORY_CREATE_SUCCESS";
export const MEDICALHISTORY_CREATE_FAIL = "MEDICALHISTORY_CREATE_FAIL";

export const MEDICALHISTORY_UPDATE_REQUEST = "MEDICALHISTORY_UPDATE_REQUEST";
export const MEDICALHISTORY_UPDATE_SUCCESS = "MEDICALHISTORY_UPDATE_SUCCESS";
export const MEDICALHISTORY_UPDATE_FAIL = "MEDICALHISTORY_UPDATE_FAIL";

export const MEDICALHISTORY_DELETE_REQUEST = "MEDICALHISTORY_DELETE_REQUEST";
export const MEDICALHISTORY_DELETE_SUCCESS = "MEDICALHISTORY_DELETE_SUCCESS";
export const MEDICALHISTORY_DELETE_FAIL = "MEDICALHISTORY_DELETE_FAIL";

export const MEDICALHISTORY_LIST_DOCTOR_REQUEST = "MEDICALHISTORY_LIST_DOCTOR_REQUEST";
export const MEDICALHISTORY_LIST_DOCTOR_SUCCESS = "MEDICALHISTORY_LIST_DOCTOR_SUCCESS";
export const MEDICALHISTORY_LIST_DOCTOR_FAIL = "MEDICALHISTORY_LIST_DOCTOR_FAIL";

export const MEDICALHISTORY_VIEW_PATIENT_REQUEST = "MEDICALHISTORY_VIEW_PATIENT_REQUEST";
export const MEDICALHISTORY_VIEW_PATIENT_SUCCESS = "MEDICALHISTORY_VIEW_PATIENT_SUCCESS";
export const MEDICALHISTORY_VIEW_PATIENT_FAIL = "MEDICALHISTORY_VIEW_PATIENT_FAIL";
