export const ORTHODONTIC_LIST_REQUEST = "ORTHODONTIC_LIST_REQUEST";
export const ORTHODONTIC_LIST_SUCCESS = "ORTHODONTIC_LIST_SUCCESS";
export const ORTHODONTIC_LIST_FAIL = "ORTHODONTIC_LIST_FAIL";

export const ORTHODONTIC_CREATE_REQUEST = "ORTHODONTIC_CREATE_REQUEST";
export const ORTHODONTIC_CREATE_SUCCESS = "ORTHODONTIC_CREATE_SUCCESS";
export const ORTHODONTIC_CREATE_FAIL = "ORTHODONTIC_CREATE_FAIL";

export const ORTHODONTIC_UPDATE_REQUEST = "ORTHODONTIC_UPDATE_REQUEST";
export const ORTHODONTIC_UPDATE_SUCCESS = "ORTHODONTIC_UPDATE_SUCCESS";
export const ORTHODONTIC_UPDATE_FAIL = "ORTHODONTIC_UPDATE_FAIL";

export const ORTHODONTIC_DELETE_REQUEST = "ORTHODONTIC_DELETE_REQUEST";
export const ORTHODONTIC_DELETE_SUCCESS = "ORTHODONTIC_DELETE_SUCCESS";
export const ORTHODONTIC_DELETE_FAIL = "ORTHODONTIC_DELETE_FAIL";
