export const PATIENT_LIST_REQUEST = "PATIENT_LIST_REQUEST";
export const PATIENT_LIST_SUCCESS = "PATIENT_LIST_SUCCESS";
export const PATIENT_LIST_FAIL = "PATIENT_LIST_FAIL";

export const PATIENT_LIST_FOR_DOCTOR_REQUEST = "PATIENT_LIST_FOR_DOCTOR_REQUEST";
export const PATIENT_LIST_FOR_DOCTOR_SUCCESS = "PATIENT_LIST_FOR_DOCTOR_SUCCESS";
export const PATIENT_LIST_FOR_DOCTOR_FAIL = "PATIENT_LIST_FOR_DOCTOR_FAIL";

export const PATIENT_LOGIN_REQUEST = "PATIENT_LOGIN_REQUEST";
export const PATIENT_LOGIN_SUCCESS = "PATIENT_LOGIN_SUCCESS";
export const PATIENT_LOGIN_FAIL = "PATIENT_LOGIN_FAIL";
export const PATIENT_LOGOUT = "PATIENT_LOGOUT";

export const PATIENT_REGISTER_REQUEST = "PATIENT_REGISTER_REQUEST";
export const PATIENT_REGISTER_SUCCESS = "PATIENT_REGISTER_SUCCESS";
export const PATIENT_REGISTER_FAIL = "PATIENT_REGISTER_FAIL";

export const PATIENT_VIEW_REQUEST = "PATIENT_VIEW_REQUEST";
export const PATIENT_VIEW_SUCCESS = "PATIENT_VIEW_SUCCESS";
export const PATIENT_VIEW_FAIL = "PATIENT_VIEW_FAIL";

export const PATIENT_UPDATE_REQUEST = "PATIENT_UPDATE_REQUEST";
export const PATIENT_UPDATE_SUCCESS = "PATIENT_UPDATE_SUCCESS";
export const PATIENT_UPDATE_FAIL = "PATIENT_UPDATE_FAIL";

export const PATIENT_DELETE_REQUEST = "PATIENT_DELETE_REQUEST";
export const PATIENT_DELETE_SUCCESS = "PATIENT_DELETE_SUCCESS";
export const PATIENT_DELETE_FAIL = "PATIENT_DELETE_FAIL";

export const PATIENT_VIEW_BY_ID_REQUEST = "PATIENT_VIEW_BY_ID_REQUEST";
export const PATIENT_VIEW_BY_ID_SUCCESS = "PATIENT_VIEW_BY_ID_SUCCESS";
export const PATIENT_VIEW_BY_ID_FAIL = "PATIENT_VIEW_BY_ID_FAIL";

export const PATIENT_UPDATE_BY_ID_REQUEST = "PATIENT_UPDATE_BY_ID_REQUEST";
export const PATIENT_UPDATE_BY_ID_SUCCESS = "PATIENT_UPDATE_BY_ID_SUCCESS";
export const PATIENT_UPDATE_BY_ID_FAIL = "PATIENT_UPDATE_BY_ID_FAIL";
