export const QUESTION_GET_REQUEST = "QUESTION_GET_REQUEST";
export const QUESTION_GET_SUCCESS = "QUESTION_GET_SUCCESS";
export const QUESTION_GET_FAIL = "QUESTION_GET_FAIL";

export const QUESTION_CREATE_REQUEST = "QUESTION_CREATE_REQUEST";
export const QUESTION_CREATE_SUCCESS = "QUESTION_CREATE_SUCCESS";
export const QUESTION_CREATE_FAIL = "QUESTION_CREATE_FAIL";

export const QUESTION_UPDATE_REQUEST = "QUESTION_UPDATE_REQUEST";
export const QUESTION_UPDATE_SUCCESS = "QUESTION_UPDATE_SUCCESS";
export const QUESTION_UPDATE_FAIL = "QUESTION_UPDATE_FAIL";

export const QUESTION_DELETE_REQUEST = "QUESTION_DELETE_REQUEST";
export const QUESTION_DELETE_SUCCESS = "QUESTION_DELETE_SUCCESS";
export const QUESTION_DELETE_FAIL = "QUESTION_DELETE_FAIL";

export const QUESTION_GETFORADMIN_REQUEST = "QUESTION_GETFORADMIN_REQUEST";
export const QUESTION_GETFORADMIN_SUCCESS = "QUESTION_GETFORADMIN_SUCCESS";
export const QUESTION_GETFORADMIN_FAIL = "QUESTION_GETFORADMIN_FAIL";

export const QUESTION_UPDATEFORADMIN_REQUEST = "QUESTION_UPDATEFORADMIN_REQUEST";
export const QUESTION_UPDATEFORADMIN_SUCCESS = "QUESTION_UPDATEFORADMIN_SUCCESS";
export const QUESTION_UPDATEFORADMIN_FAIL = "QUESTION_UPDATEFORADMIN_FAIL";

export const QUESTION_DELETEFORADMIN_REQUEST = "QUESTION_DELETEFORADMIN_REQUEST";
export const QUESTION_DELETEFORADMIN_SUCCESS = "QUESTION_DELETEFORADMIN_SUCCESS";
export const QUESTION_DELETEFORADMIN_FAIL = "QUESTION_DELETEFORADMIN_FAIL";

export const COMMONQUESTION_GET_REQUEST = "COMMONQUESTION_GET_REQUEST";
export const COMMONQUESTION_GET_SUCCESS = "COMMONQUESTION_GET_SUCCESS";
export const COMMONQUESTION_GET_FAIL = "COMMONQUESTION_GET_FAIL";
